<a href="https://colab.research.google.com/github/Samin-Sadaf7/ML_practice/blob/main/MachineLearningPractice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Import numpy Library
import numpy as np

In [ ]:
!pip install pandas

Create a vector with numpy library

In [ ]:
# Creating a vector as a row
vector_row = np.array([1,2,3])
# Creating a vector as a column
vector_column = np.array([[1],[2],[3]])# creating a multidimensional array but
# with a single column
print(vector_row)
print(vector_column)

[1 2 3]
[[1]
 [2]
 [3]]


Creating a Matrix with numpy library

In [ ]:
#Creating a Multidimensional Array
matrix_with_multidimensional_array = np.array([[1,2],
                  [2,3],
                  [3,4]])
print(matrix_with_multidimensional_array)
#Using builtin mat function of numpy
matrix_with_builtin_mat = np.mat([[1,2],[2,4], [3,2]])
print(matrix_with_builtin_mat)

[[1 2]
 [2 3]
 [3 4]]
[[1 2]
 [2 4]
 [3 2]]


In [ ]:
from scipy import sparse
#creating a matrix
matrix = np.array([[0,0,2], [0,1,0],[3,0,0]])
matrix_sparse = sparse.csr_matrix(matrix)
print(matrix_sparse)

  (0, 2)	2
  (1, 1)	1
  (2, 0)	3


##Panda Library
The most important part of Panda Library is its DataFrame. It can be thought of as a table in Sheets(Excel).

We will take the path of csv file and read and describe it using panda.

In [ ]:
#at first let's import panda
import pandas as pd
california_housing_test = "/content/sample_data/california_housing_test.csv"
cal_house_test  = pd.read_csv(california_housing_test)
cal_house_test.describe()

longitude    latitude  housing_median_age   total_rooms  \
count  3000.000000  3000.00000         3000.000000   3000.000000   
mean   -119.589200    35.63539           28.845333   2599.578667   
std       1.994936     2.12967           12.555396   2155.593332   
min    -124.180000    32.56000            1.000000      6.000000   
25%    -121.810000    33.93000           18.000000   1401.000000   
50%    -118.485000    34.27000           29.000000   2106.000000   
75%    -118.020000    37.69000           37.000000   3129.000000   
max    -114.490000    41.92000           52.000000  30450.000000   

       total_bedrooms    population  households  median_income  \
count     3000.000000   3000.000000  3000.00000    3000.000000   
mean       529.950667   1402.798667   489.91200       3.807272   
std        415.654368   1030.543012   365.42271       1.854512   
min          2.000000      5.000000     2.00000       0.499900   
25%        291.000000    780.000000   273.00000       2.544000   
50%        437.000000   1155.000000   409.50000       3.487150   
75%        636.000000   1742.750000   597.25000       4.656475   
max       5419.000000  11935.000000  4930.00000      15.000100   

       median_house_value  
count          3000.00000  
mean         205846.27500  
std          113119.68747  
min           22500.00000  
25%          121200.00000  
50%          177650.00000  
75%          263975.00000  
max          500001.00000

To many variables to think of and to print . Also some variables has missing values. Let's drop them for now

In [ ]:
cal_house_test.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value'],
      dtype='object')

In [ ]:
cal_house_test = cal_house_test.dropna(axis=0)
cal_house_test.head(5)

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.05     37.37                27.0       3885.0           661.0   
1    -118.30     34.26                43.0       1510.0           310.0   
2    -117.81     33.78                27.0       3589.0           507.0   
3    -118.36     33.82                28.0         67.0            15.0   
4    -119.67     36.33                19.0       1241.0           244.0   

   population  households  median_income  median_house_value  
0      1537.0       606.0         6.6085            344700.0  
1       809.0       277.0         3.5990            176500.0  
2      1484.0       495.0         5.7934            270500.0  
3        49.0        11.0         6.1359            330000.0  
4       850.0       237.0         2.9375             81700.0

Setting up the predication variable

In [ ]:
y=cal_house_test.median_house_value

Setting up features

In [ ]:
cal_house_features = ['longitude', 'latitude','total_rooms','total_bedrooms', 'housing_median_age','median_income']
X= cal_house_test[cal_house_features]

In [ ]:
X.head()

longitude  latitude  total_rooms  total_bedrooms  housing_median_age  \
0    -122.05     37.37       3885.0           661.0                27.0   
1    -118.30     34.26       1510.0           310.0                43.0   
2    -117.81     33.78       3589.0           507.0                27.0   
3    -118.36     33.82         67.0            15.0                28.0   
4    -119.67     36.33       1241.0           244.0                19.0   

   median_income  
0         6.6085  
1         3.5990  
2         5.7934  
3         6.1359  
4         2.9375

In [ ]:
X.describe()

longitude    latitude   total_rooms  total_bedrooms  \
count  3000.000000  3000.00000   3000.000000     3000.000000   
mean   -119.589200    35.63539   2599.578667      529.950667   
std       1.994936     2.12967   2155.593332      415.654368   
min    -124.180000    32.56000      6.000000        2.000000   
25%    -121.810000    33.93000   1401.000000      291.000000   
50%    -118.485000    34.27000   2106.000000      437.000000   
75%    -118.020000    37.69000   3129.000000      636.000000   
max    -114.490000    41.92000  30450.000000     5419.000000   

       housing_median_age  median_income  
count         3000.000000    3000.000000  
mean            28.845333       3.807272  
std             12.555396       1.854512  
min              1.000000       0.499900  
25%             18.000000       2.544000  
50%             29.000000       3.487150  
75%             37.000000       4.656475  
max             52.000000      15.000100

##Create the Model:


1.  Define:
            Type of Model should it be?:
            Some other type of model?
            Parameters of that model need to specified as well
2.  Fit:
           Capture patterns from the provided data.
           The most important part of the modeling
3.  Predict:
            Predict the Y value
4.  Evaluate:
            Determine the accuracy of the predication.

Using scikit learn library for model. We are going to use.

DecisionTreeRegressor(random_state=1)

Many machine learning models allow some randomness in model training. Specifying a number for random_state ensures you get the same results in each run. The number chosen for random state won't affect the quality of model meaningfully.

In [ ]:
from sklearn.tree import DecisionTreeRegressor
# Defining the model and specifying the random state
cal_house_model = DecisionTreeRegressor(random_state=1)
# Fit the model
cal_house_model.fit(X,y)

DecisionTreeRegressor(random_state=1)

In [ ]:
#Now making prediction
print("Making predictions for the following 5 houses:")
print(X.head())
print("The predictions are")
print(cal_house_model.predict(X.head()))

Making predictions for the following 5 houses:
   longitude  latitude  total_rooms  total_bedrooms  housing_median_age  \
0    -122.05     37.37       3885.0           661.0                27.0   
1    -118.30     34.26       1510.0           310.0                43.0   
2    -117.81     33.78       3589.0           507.0                27.0   
3    -118.36     33.82         67.0            15.0                28.0   
4    -119.67     36.33       1241.0           244.0                19.0   

   median_income  
0         6.6085  
1         3.5990  
2         5.7934  
3         6.1359  
4         2.9375  
The predictions are
[344700. 176500. 270500. 330000.  81700.]


###Model Validation
We will create a validation set by splitting the training set . Use a set for fitting the model and other set to see the accuracy

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error
# split data into training and validation data, for both features and target
# The split is based on a random number generator. Supplying a numeric value to
# the random_state argument guarantees we get the same split every time we
# run this script.
train_X, val_X, train_y, val_y = train_test_split(X, y, random_state = 0)
# Define model
cal_model = DecisionTreeRegressor()
# Fit model
cal_model.fit(train_X, train_y)

# get predicted prices on validation data
val_predictions = cal_model.predict(val_X)
print(mean_absolute_error(val_y, val_predictions))

57015.912


###Underfitting and Overfitting
controlling the depth of decision trees.

Here's the takeaway:
Models can suffer from either:
Overfitting:
  capturing spurious patterns that won't recur in the future, leading to less accurate predictions
Underfitting:
  failing to capture relevant patterns, again leading to less accurate predictions.

In [ ]:
from sklearn.metrics import mean_absolute_error
from sklearn.tree import DecisionTreeRegressor

def get_mae(max_leaf_nodes, train_X, val_X, train_y, val_y):
    model = DecisionTreeRegressor(max_leaf_nodes=max_leaf_nodes, random_state=0)
    model.fit(train_X, train_y)
    preds_val = model.predict(val_X)
    mae = mean_absolute_error(val_y, preds_val)
    return(mae)

In [ ]:
# compare MAE with differing values of max_leaf_nodes
for max_leaf_nodes in [5, 50, 500, 5000]:
    my_mae = get_mae(max_leaf_nodes, train_X, val_X, train_y, val_y)
    print("Max leaf nodes: %d  \t\t Mean Absolute Error:  %d" %(max_leaf_nodes, my_mae))

Max leaf nodes: 5  		 Mean Absolute Error:  64204
Max leaf nodes: 50  		 Mean Absolute Error:  55226
Max leaf nodes: 500  		 Mean Absolute Error:  57108
Max leaf nodes: 5000  		 Mean Absolute Error:  58951


In [ ]:
final_model = DecisionTreeRegressor(max_leaf_nodes = 50)
final_model.fit(train_X, train_y)
val_pred=final_model.predict(val_X)
print(mean_absolute_error(val_y, val_pred))

55226.29082346741


###Random Forest Algorithm
For a single decision tree, too deep with lots of leaves can overfit the data because lot of the information coming from historic data from a very few data points. Too shallow tree can not capture distinctions from the raw data.
In random forest , instead of a single tree , we have multiple trees and average the prediction of all the predictions of the trees to get the prediction of the random forest. It has better accuracy then single tree and it can work well with default parameters which is unlikely for other better performing models as well.

In [ ]:
from sklearn.ensemble import RandomForestRegressor
forest_model = RandomForestRegressor(random_state=1)
forest_model.fit(train_X, train_y)
forest_model_predictions =forest_model.predict(val_X)
print(mean_absolute_error(val_y, forest_model_predictions))

42007.042160000005


Random Forest works better than decision tree without even tuning

###Dealing with Missing Values
Many reasonss missing value could appear in the dataset. Most ML algorithms will give error for missing values. There are 3 options to choose from:
1. Drop columns with missing values:
        Unless most of the values of that column is missing by this approach model looses lots of important data
2. Imputation:
        A better approach than Drop columns with missing values. Fill in the mean value along each column. Give more accuracy than previous approach
3. An Extension to Imputation:
        Mean value can be above or below the original value. Rows with missing values can be unique as well. Therefore, sometimes it is better to look for which value is missing and put on that row. But in this case, we need an additional column to tell which entries were originally missing in the original dataset.

In [ ]:
#Load the data
cal_train_dataset = pd.read_csv(california_housing_test)
cal_train_dataset.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value'],
      dtype='object')

In [ ]:
# To keep things simple, we'll use only numerical predictors
cal_predictors = cal_train_dataset.drop(['median_house_value'], axis=1)
X = cal_predictors.select_dtypes(exclude=['object'])

# Divide data into training and validation subsets
X_train, X_valid, y_train, y_valid = train_test_split(X, y, train_size=0.8, test_size=0.2, random_state=0)

In [ ]:
# Function for comparing different approaches
def score_dataset(X_train, X_valid, y_train, y_valid):
    model = RandomForestRegressor(n_estimators=10, random_state=0)
    model.fit(X_train, y_train)
    preds = model.predict(X_valid)
    return mean_absolute_error(y_valid, preds)

In [ ]:
#Get the columns of missing values
cols_with_missing_values = [col for col in X_train.columns
                            if X_train[col].isnull().any()]
print(cols_with_missing_values)

[]


In [ ]:
#Drop columns in training and validation data set
Reduced_training_X = X_train.drop(cols_with_missing_values, axis=1)
Reduced_validation_X = X_valid.drop(cols_with_missing_values, axis=1)
print("MAE from Approach 1 (Drop columns with missing values):")
print(score_dataset(Reduced_training_X, Reduced_validation_X, y_train, y_valid))

MAE from Approach 1 (Drop columns with missing values):
43784.635


In [ ]:
#Using simple imputer for Imputation
from sklearn.impute import SimpleImputer
#Imputation
imputer = SimpleImputer()
imputed_X_train = pd.DataFrame(imputer.fit_transform(X_train))
imputed_X_valid = pd.DataFrame(imputer.transform(X_valid))

# Imputation removed column names; put them back
imputed_X_train.columns = X_train.columns
imputed_X_valid.columns = X_valid.columns

print("MAE from Approach 2 (Imputation):")
print(score_dataset(imputed_X_train, imputed_X_valid, y_train, y_valid))

MAE from Approach 2 (Imputation):
43784.635


In [ ]:
#An Extension of Imputation
#make a copy to avoid changing the original dataset
X_train_new = X_train.copy()
X_valid_new = X_valid.copy()
# Make a column indication which value has imputed
for col in cols_with_missing_values:
  X_train_new[col + '_was_missing'] = X_train_new[col].isnull()
  X_valid_new[col + '_was_missing'] = X_valid_new[col].isnull()

#Imputation
Imputed_X_train_new = pd.DataFrame(imputer.fit_transform(X_train_new))
Imputed_X_valid_new = pd.DataFrame(imputer.transform(X_valid_new))

Imputed_X_train_new.columns = X_train_new.columns
Imputed_X_valid_new.columns = X_valid_new.columns

print("MAE from Approach 3 (An Extension to Imputation):")
print(score_dataset(Imputed_X_train_new, Imputed_X_valid_new, y_train, y_valid))


MAE from Approach 3 (An Extension to Imputation):
43784.635


In [ ]:
# Shape of training data (num_rows, num_columns)
print(X_train.shape)

# Number of missing values in each column of training data
missing_val_count_by_column = (X_train.isnull().sum())
print(missing_val_count_by_column[missing_val_count_by_column > 0])

(2400, 8)
Series([], dtype: int64)


###Categorical Variables

Categorical Variables are variables which can have a limited number of values. If we do not preprocess them first, we will get error in most of the machine learning models.
#####Approaches to use:
1. Drop Categorical variables:
         Only works if the columns  did not contain any useful information
2. Ordinal Encoding:
          Assign unique values to a different integer.
          It will only make sense if the values have an indisputable ranking. We have order to those variables.
3. One-shot Encoding:
          Create new columns indicating the presence of each possible value in the original data.
          
          In the original dataset, "Color" is a categorical variable with three categories: "Red", "Yellow", and "Green".
          The corresponding one-hot encoding contains one column for each possible value, and one row for each row in the original dataset.
          Wherever the original value was "Red", we put a 1 in the "Red" column; if the original value was "Yellow", we put a 1 in the "Yellow" column, and so on.
          
          In contrast to ordinal encoding, one-hot encoding does not assume an ordering of the categories.
          Thus, you can expect this approach to work particularly well if there is no clear ordering in the categorical data (e.g., "Red" is neither more nor less than "Yellow").
           We refer to categorical variables without an intrinsic ranking as nominal variables.
          
          One-hot encoding generally does not perform well if the categorical variable takes on a large number of values (i.e., you generally won't use it for variables taking more than 15 different values).

In [ ]:
X_train.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
2370    -122.05     37.31                25.0       4601.0           696.0   
1774    -118.16     33.96                24.0       1635.0           507.0   
731     -121.69     36.62                19.0       1907.0           323.0   
271     -121.96     37.33                35.0       2294.0           411.0   
1077    -122.30     37.81                52.0        572.0           109.0   

      population  households  median_income  
2370      2003.0       666.0         8.0727  
1774      2480.0       481.0         2.4432  
731        681.0       270.0         6.0332  
271       1054.0       449.0         4.0667  
1077       274.0        82.0         1.8516

In [ ]:
s = (X_train.dtypes=='object')
object_cols = list(s[s].index)
print("Categorical variables:")
print(object_cols)

Categorical variables:
[]


In [ ]:
drop_X_train = X_train.select_dtypes(exclude=['object'])
drop_X_valid = X_valid.select_dtypes(exclude=['object'])

print("MAE from Approach 1 (Drop categorical variables):")
print(score_dataset(drop_X_train, drop_X_valid, y_train, y_valid))

MAE from Approach 1 (Drop categorical variables):
43784.635


In [ ]:
from sklearn.preprocessing import OrdinalEncoder

# Make copy to avoid changing original data
label_X_train = X_train.copy()
label_X_valid = X_valid.copy()

# Apply ordinal encoder to each column with categorical data
ordinal_encoder = OrdinalEncoder()
label_X_train[object_cols] = ordinal_encoder.fit_transform(X_train[object_cols])
label_X_valid[object_cols] = ordinal_encoder.transform(X_valid[object_cols])

print("MAE from Approach 2 (Ordinal Encoding):")
print(score_dataset(label_X_train, label_X_valid, y_train, y_valid))

MAE from Approach 2 (Ordinal Encoding):
43784.635


In [ ]:
from sklearn.preprocessing import OneHotEncoder

# Apply one-hot encoder to each column with categorical data
OH_encoder = OneHotEncoder(handle_unknown='ignore', sparse=False)
# --->  handle_unknown, ignore :: to avoid error for validation data contains classes
# not contained by training dataset
# Sparse means we do not need to output a sparse matrix instead we need a numpy array
OH_cols_train = pd.DataFrame(OH_encoder.fit_transform(X_train[object_cols]))
OH_cols_valid = pd.DataFrame(OH_encoder.transform(X_valid[object_cols]))

# One-hot encoding removed index; put it back
OH_cols_train.index = X_train.index
OH_cols_valid.index = X_valid.index

# Remove categorical columns (will replace with one-hot encoding)
num_X_train = X_train.drop(object_cols, axis=1)
num_X_valid = X_valid.drop(object_cols, axis=1)

# Add one-hot encoded columns to numerical features
OH_X_train = pd.concat([num_X_train, OH_cols_train], axis=1)
OH_X_valid = pd.concat([num_X_valid, OH_cols_valid], axis=1)

# Ensure all columns have string type
OH_X_train.columns = OH_X_train.columns.astype(str)
OH_X_valid.columns = OH_X_valid.columns.astype(str)

print("MAE from Approach 3 (One-Hot Encoding):")
print(score_dataset(OH_X_train, OH_X_valid, y_train, y_valid))

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


MAE from Approach 3 (One-Hot Encoding):
43784.635
