<a href="https://colab.research.google.com/github/Samin-Sadaf7/ML_practice/blob/main/MachineLearningPractice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Import numpy Library
import numpy as np

In [2]:
!pip install pandas

Create a vector with numpy library

In [3]:
# Creating a vector as a row
vector_row = np.array([1,2,3])
# Creating a vector as a column
vector_column = np.array([[1],[2],[3]])# creating a multidimensional array but
# with a single column
print(vector_row)
print(vector_column)

[1 2 3]
[[1]
 [2]
 [3]]


Creating a Matrix with numpy library

In [4]:
#Creating a Multidimensional Array
matrix_with_multidimensional_array = np.array([[1,2],
                  [2,3],
                  [3,4]])
print(matrix_with_multidimensional_array)
#Using builtin mat function of numpy
matrix_with_builtin_mat = np.mat([[1,2],[2,4], [3,2]])
print(matrix_with_builtin_mat)

[[1 2]
 [2 3]
 [3 4]]
[[1 2]
 [2 4]
 [3 2]]


In [5]:
from scipy import sparse
#creating a matrix
matrix = np.array([[0,0,2], [0,1,0],[3,0,0]])
matrix_sparse = sparse.csr_matrix(matrix)
print(matrix_sparse)

  (0, 2)	2
  (1, 1)	1
  (2, 0)	3


##Panda Library
The most important part of Panda Library is its DataFrame. It can be thought of as a table in Sheets(Excel).

We will take the path of csv file and read and describe it using panda.

In [6]:
#at first let's import panda
import pandas as pd
california_housing_test = "/content/sample_data/california_housing_test.csv"
cal_house_test  = pd.read_csv(california_housing_test)
cal_house_test.describe()

longitude    latitude  housing_median_age   total_rooms  \
count  3000.000000  3000.00000         3000.000000   3000.000000   
mean   -119.589200    35.63539           28.845333   2599.578667   
std       1.994936     2.12967           12.555396   2155.593332   
min    -124.180000    32.56000            1.000000      6.000000   
25%    -121.810000    33.93000           18.000000   1401.000000   
50%    -118.485000    34.27000           29.000000   2106.000000   
75%    -118.020000    37.69000           37.000000   3129.000000   
max    -114.490000    41.92000           52.000000  30450.000000   

       total_bedrooms    population  households  median_income  \
count     3000.000000   3000.000000  3000.00000    3000.000000   
mean       529.950667   1402.798667   489.91200       3.807272   
std        415.654368   1030.543012   365.42271       1.854512   
min          2.000000      5.000000     2.00000       0.499900   
25%        291.000000    780.000000   273.00000       2.544000   
50%        437.000000   1155.000000   409.50000       3.487150   
75%        636.000000   1742.750000   597.25000       4.656475   
max       5419.000000  11935.000000  4930.00000      15.000100   

       median_house_value  
count          3000.00000  
mean         205846.27500  
std          113119.68747  
min           22500.00000  
25%          121200.00000  
50%          177650.00000  
75%          263975.00000  
max          500001.00000

To many variables to think of and to print . Also some variables has missing values. Let's drop them for now

In [7]:
cal_house_test.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value'],
      dtype='object')

In [8]:
cal_house_test = cal_house_test.dropna(axis=0)
cal_house_test.head(5)

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.05     37.37                27.0       3885.0           661.0   
1    -118.30     34.26                43.0       1510.0           310.0   
2    -117.81     33.78                27.0       3589.0           507.0   
3    -118.36     33.82                28.0         67.0            15.0   
4    -119.67     36.33                19.0       1241.0           244.0   

   population  households  median_income  median_house_value  
0      1537.0       606.0         6.6085            344700.0  
1       809.0       277.0         3.5990            176500.0  
2      1484.0       495.0         5.7934            270500.0  
3        49.0        11.0         6.1359            330000.0  
4       850.0       237.0         2.9375             81700.0

Setting up the predication variable

In [9]:
y=cal_house_test.median_house_value

Setting up features

In [10]:
cal_house_features = ['longitude', 'latitude','total_rooms','total_bedrooms', 'housing_median_age','median_income']
X= cal_house_test[cal_house_features]

In [11]:
X.head()

longitude  latitude  total_rooms  total_bedrooms  housing_median_age  \
0    -122.05     37.37       3885.0           661.0                27.0   
1    -118.30     34.26       1510.0           310.0                43.0   
2    -117.81     33.78       3589.0           507.0                27.0   
3    -118.36     33.82         67.0            15.0                28.0   
4    -119.67     36.33       1241.0           244.0                19.0   

   median_income  
0         6.6085  
1         3.5990  
2         5.7934  
3         6.1359  
4         2.9375

In [12]:
X.describe()

longitude    latitude   total_rooms  total_bedrooms  \
count  3000.000000  3000.00000   3000.000000     3000.000000   
mean   -119.589200    35.63539   2599.578667      529.950667   
std       1.994936     2.12967   2155.593332      415.654368   
min    -124.180000    32.56000      6.000000        2.000000   
25%    -121.810000    33.93000   1401.000000      291.000000   
50%    -118.485000    34.27000   2106.000000      437.000000   
75%    -118.020000    37.69000   3129.000000      636.000000   
max    -114.490000    41.92000  30450.000000     5419.000000   

       housing_median_age  median_income  
count         3000.000000    3000.000000  
mean            28.845333       3.807272  
std             12.555396       1.854512  
min              1.000000       0.499900  
25%             18.000000       2.544000  
50%             29.000000       3.487150  
75%             37.000000       4.656475  
max             52.000000      15.000100

##Create the Model:


1.  Define:
            Type of Model should it be?:
            Some other type of model?
            Parameters of that model need to specified as well
2.  Fit:
           Capture patterns from the provided data.
           The most important part of the modeling
3.  Predict:
            Predict the Y value
4.  Evaluate:
            Determine the accuracy of the predication.

Using scikit learn library for model. We are going to use.

DecisionTreeRegressor(random_state=1)

Many machine learning models allow some randomness in model training. Specifying a number for random_state ensures you get the same results in each run. The number chosen for random state won't affect the quality of model meaningfully.

In [13]:
from sklearn.tree import DecisionTreeRegressor
# Defining the model and specifying the random state
cal_house_model = DecisionTreeRegressor(random_state=1)
# Fit the model
cal_house_model.fit(X,y)

DecisionTreeRegressor(random_state=1)

In [14]:
#Now making prediction
print("Making predictions for the following 5 houses:")
print(X.head())
print("The predictions are")
print(cal_house_model.predict(X.head()))

Making predictions for the following 5 houses:
   longitude  latitude  total_rooms  total_bedrooms  housing_median_age  \
0    -122.05     37.37       3885.0           661.0                27.0   
1    -118.30     34.26       1510.0           310.0                43.0   
2    -117.81     33.78       3589.0           507.0                27.0   
3    -118.36     33.82         67.0            15.0                28.0   
4    -119.67     36.33       1241.0           244.0                19.0   

   median_income  
0         6.6085  
1         3.5990  
2         5.7934  
3         6.1359  
4         2.9375  
The predictions are
[344700. 176500. 270500. 330000.  81700.]


###Model Validation
We will create a validation set by splitting the training set . Use a set for fitting the model and other set to see the accuracy

In [15]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error
# split data into training and validation data, for both features and target
# The split is based on a random number generator. Supplying a numeric value to
# the random_state argument guarantees we get the same split every time we
# run this script.
train_X, val_X, train_y, val_y = train_test_split(X, y, random_state = 0)
# Define model
cal_model = DecisionTreeRegressor()
# Fit model
cal_model.fit(train_X, train_y)

# get predicted prices on validation data
val_predictions = cal_model.predict(val_X)
print(mean_absolute_error(val_y, val_predictions))

59076.58


###Underfitting and Overfitting
controlling the depth of decision trees.

Here's the takeaway:
Models can suffer from either:
Overfitting:
  capturing spurious patterns that won't recur in the future, leading to less accurate predictions
Underfitting:
  failing to capture relevant patterns, again leading to less accurate predictions.

In [16]:
from sklearn.metrics import mean_absolute_error
from sklearn.tree import DecisionTreeRegressor

def get_mae(max_leaf_nodes, train_X, val_X, train_y, val_y):
    model = DecisionTreeRegressor(max_leaf_nodes=max_leaf_nodes, random_state=0)
    model.fit(train_X, train_y)
    preds_val = model.predict(val_X)
    mae = mean_absolute_error(val_y, preds_val)
    return(mae)

In [17]:
# compare MAE with differing values of max_leaf_nodes
for max_leaf_nodes in [5, 50, 500, 5000]:
    my_mae = get_mae(max_leaf_nodes, train_X, val_X, train_y, val_y)
    print("Max leaf nodes: %d  \t\t Mean Absolute Error:  %d" %(max_leaf_nodes, my_mae))

Max leaf nodes: 5  		 Mean Absolute Error:  64204
Max leaf nodes: 50  		 Mean Absolute Error:  55226
Max leaf nodes: 500  		 Mean Absolute Error:  57108
Max leaf nodes: 5000  		 Mean Absolute Error:  58951


In [18]:
final_model = DecisionTreeRegressor(max_leaf_nodes = 5000)
final_model.fit(train_X, train_y)
val_pred=final_model.predict(val_X)
print(mean_absolute_error(val_y, val_pred))

58232.71333333333


###Random Forest Algorithm
For a single decision tree, too deep with lots of leaves can overfit the data because lot of the information coming from historic data from a very few data points. Too shallow tree can not capture distinctions from the raw data.
In random forest , instead of a single tree , we have multiple trees and average the prediction of all the predictions of the trees to get the prediction of the random forest. It has better accuracy then single tree and it can work well with default parameters which is unlikely for other better performing models as well.

In [21]:
from sklearn.ensemble import RandomForestRegressor
forest_model = RandomForestRegressor(random_state=1)
forest_model.fit(train_X, train_y)
forest_model_predictions =forest_model.predict(val_X)
print(mean_absolute_error(val_y, forest_model_predictions))

42007.042160000005


Random Forest works better than decision tree without even tuning